GruntFile.js

@steveoh Please review. Just wanted you to be aware.

better settings for projects with lots of tests

---

GruntFile.js
package.json

add jshint stylish

---

src/app/resources/App.css

modify version placement

---

.eslintrc
package.json
src/ChangeLog.html

This enables this setting in the eslint atom linter plugin to work:

eslint html plugin

---

.lgtm
BUILD_STEPS.md
GruntFile.js
LICENSE.md
MAINTAINERS
_SpecRunner.html
bower.json
package.json
profiles/build.profile.js
src/app/App.js
src/app/Identify.js
src/app/config.js
src/app/packages.js
src/index.html

i'm going to deploy this to mapserv to make sure it works in preperation for bringing atlas back home. It won't be active yet so if we have any issues we can address them in this pr and update the deployment.

3.x enhancements

---

src/app/config.js

version 1.5.0 of the search soe has the logic for the raster dems now. I also fixed a bug where the meter value was actually returning the object id. That fix was deployed today. This is ready for a build whenever.

switch to new dem

---

src/app/config.js

servers not in production yet but will be soooon?

update land ownership url

---

src/App.js
src/components/MouseTrap/MouseTrap.js

Here's a possible implementation of a render prop for MouseTrap.

feat: implement render prop for MouseTrap component

---

.travis.yml

https://docs.travis-ci.com/user/caching/#npm-cache

fix: cleaner travis npm cache config

---

.firebaserc
.github/workflows/nodejs.yml
firebase.json

this allows us to host prod and dev in the same firebase project

multi target deployment to firebase

---

package-lock.json
package.json

chore: :evergreen_tree:

---

.github/workflows/nodejs.yml
package-lock.json
package.json
src/components/Identify/Identify.js

update to jsapi 4.22

---

.github/dependabot.yml
.github/workflows/nodejs.yml
firebase.json
package-lock.json
package.json

Correct a few missing/wrong things

---

.github/workflows/nodejs.yml

ci: update action versions

---

.firebaserc
.github/workflows/nodejs.yml
firebase.json
package-lock.json
package.json

chore: may dependency updates

---

package-lock.json
package.json

chore: August updates

---

package-lock.json
package.json

fix: update packages to fix opacity issue

---

.github/workflows/pull_request.yml
package-lock.json
package.json

January dependency updates

---

CHANGELOG.md
package-lock.json
package.json

update printing quad word url

---

CHANGELOG.md
package-lock.json
package.json
src/components/esrijs/MapView.jsx

Migrate to SITLA vector tiles

---

src/App.tsx
src/components/MapContainer.tsx

Using the lite draft vector tiles and a bug fix

Some bug fixes

---

.github/workflows/pull_request.yml
.github/workflows/release.yml

https://pnpm.io/cli/run#options
Fixes #
Changes proposed in this pull request:
-
-

ci: fix pnpm run parameters

---

src/components/MapContainer.tsx

Ref: https://github.com/agrc/kitchen-sink/issues/460

fix: remove overlay because of bug in layer selector
